# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-29 19:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=datetime.datetime(2018, 12, 29, 19, 24, 34, 18095, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
