# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-31 13:27
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_posts_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='posts',
            name='videofile',
            field=models.FileField(null=True, upload_to=blog.models.upload_location),
        ),
    ]
