# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-06 19:39
from __future__ import unicode_literals

import blog.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190107_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(default=datetime.datetime(2019, 1, 6, 19, 39, 29, 480934, tzinfo=utc), upload_to=blog.models.upload_location),
            preserve_default=False,
        ),
    ]
