# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-06 22:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190107_0318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='fullname',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact',
            field=models.CharField(default=datetime.datetime(2019, 1, 6, 22, 17, 16, 129285, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
    ]
